name: Mon Flux de travail

on:
  push:
    branches:
    - 'main'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dÃ©pÃ´t
        uses: actions/checkout@v2

      - name: Installer Rust avec Cargo and typeshare
        run: make install_rust && make install_typeshare_cli

      - name: generate ts
        run: make generate_ts

      - name: generate package
        run: make run_rust_script_ts

      - name: up minor version
        run: make up_version_minor_ts



      - name: Use Node.js And Login to NPM and Publish Package
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: cd ts && npm install && cat package.json && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_KEY }}" > .npmrc && npm publish

